### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Savecoders/Savior-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Savecoders** [comment]
thx, I will investigate how to add a license, thank you very much for your recommendation and for see the zsh theme.

**Comment by Savecoders** [comment]
Hi, I just added a MIT lincense to the repository, thanks for the recommendation.  🫡
